nodeLinker: node-modules
cacheFolder: "./.yarn/cache"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

enableGlobalCache: true

compressionLevel: 0

npmRegistryServer: "https://registry.npmjs.org"

logFilters:
  - code: YN0013 # Peer dependency warnings
    level: discard
  - code: YN0002 # Missing peer dependency
    level: warning

packageExtensions:
  "vite@*":
    peerDependencies:
      "@types/node": "*"
