cacheFolder: ./.yarn/cache

compressionLevel: 0

enableGlobalCache: true

logFilters:
  - code: YN0013
    level: discard
  - code: YN0002
    level: warning

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  vite@*:
    peerDependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
